# NatLibFi/Melinda maintenance strategy
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/Helsinki"

  # Minor updates to npm versions daily
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:45"
      timezone: "Europe/Helsinki"
    target-branch: "maintenance"
    versioning-strategy: lockfile-only
    labels:
      - "npm dependencies"
    reviewers:
      - "natlibfi/melinda-js-lead"

  # Major updates to npm versions weekly @friday
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "07:00"
      timezone: "Europe/Helsinki"
    target-branch: "maintenance"
    versioning-strategy: increase-if-necessary
    labels:
      - "npm dependencies"
    reviewers:
      - "natlibfi/melinda-js-lead"