---
kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod o+w /drone/src
- name: test
  image: node:8
  user: node
  commands:
  - npm install
  - npm test
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-record-import-importer-helmet
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [master, test]
event: [push, tag]
---
kind: secret
name: docker_username
data: MhMGGOsj5qIy1Xj5wnCtpOtCqZ+tbR9RO+4KXdx9H/OiIJamQwmVxwv5W44WrZX7fqQ=
---
kind: secret
name: docker_password
data: 8a0n4yrVV96WuAw+LhCN0NQ8XnFswPiZJUjkOPkfsxuZIJ+RqG36ODAWlSlXaC272QLa3NxnJWTDgdZ8MCZ19guah32EZbrw8ps9ujiF+tLpjg4DoQ8sMWwdyx4=
---
kind: signature
hmac: 190c714a37ae7fc9e92dc31c0288371a9417ad9706abae1ae9460b4d6ab1e2fb

...
