---
kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod o+w /drone/src
- name: test
  image: node:8
  user: node  
  commands:
  - npm install
  - npm test
- name: docker 
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-record-import-importer-helmet
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [master, test]
event: [push, tag]
---
kind: signature
hmac: 2c236d94f93963a5cff40b7ce06e3f2cdd87e9d95fc0aaad4ac32818d4783e8a

...
