# Melinda node tests

name: Melinda node tests

on: push

jobs:
  build-node-versions:
    name: Node version matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      env:
        NPM_CONFIG_IGNORE_SCRIPTS: true
    - run: npm audit --package-lock-only --production --audit-level=moderate
    - run: npm ci
    - run: npm test
    - run: npm run build --if-present

  njsscan:
    name: Njsscan check
    needs: build-node-versions
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'

  quayio:
    name: Image builder & deployer
    needs: njsscan
    runs-on: ubuntu-latest

    env:
      image_name: ${{ github.repository }}
      GIT_EVENT_NAME: ${{ github.event_name }}
      GIT_REF_NAME: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v2
      - name: Get image tags
        id: image_tags
        run: |
          echo -n ::set-output name=IMAGE_TAGS::
          if test "$GIT_EVENT_NAME" = 'push';then
            if test "$GIT_REF_NAME" = 'master';then
              echo "latest"
            elif test "$GIT_REF_NAME" = 'main';then
              echo "latest"
            else
              echo "$GIT_REF_NAME"
            fi
          else test "$GIT_EVENT_NAME" = 'tag';then
            echo "$GIT_REF_NAME"
          fi
      - name: Build and publish image to Quay
        uses: docker/build-push-action@v1
        with:
          registry: quay.io
          repository: natlibfi/${{ env.image_name }}
          username: ${{ secrets.MELINDA_QUAY_IO_USERNAME }}
          password: ${{ secrets.MELINDA_QUAY_IO_PASSWORD }}
          tags: "${{ steps.image_tags.outputs.IMAGE_TAGS }}"